---
title: "S.E. Lang: Satellite Remote Sensing of Water Quality, Data Processing and Analysis"
author: "Sarah Lang"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load, warning=FALSE}
library(ICC)
library(ggplot2)
library(car)
library(RColorBrewer)
library(broom)
library(plyr)
library(dplyr)
library(zoo)
library(Metrics)
library(scales)
library(tidyr)
library(grid) #create tables
library(gridExtra)
library(stats) #used for AIC
library(lme4) #mixed modeling
library(apaTables) #export APA tables
library(patchwork) #data visualization package
library(rMR) #oxygen calculation package

setwd("/Users/sarahlang/Desktop/modeling_and_analysis/")

#data for Part 1: Statistical Water Quality Model
data<-read.csv("matchup.csv") #dataframe for comparing in situ vs. satellite
histdat<-read.csv("histogram_data.csv") #dataframe for histogram
sat_timedata<-read.csv('sat_timedata.csv') #dataframe with satellite data, dates, and yeardays

#data for Part 2: Comparing Landsat-8 and Sentinel-2
comparedata<-read.csv("compare_L8S2.csv") #dataframe to compare Secchi depths (Zsd) from each satellite

#data for Part 3: Atmospheric Correction Assessment
atmocorrect<-read.csv('atmocorrect.csv') #comparing values from l2gen (NASA SeaDAS) and ACOLITE (REMSEM)

#data for Part 4: Water Quality Drivers, exploratory analysis. 
#This data comes from: doi:10.6073/pasta/db7f8fe720ddfcdfab1352adc9c22702
#McGlathery, K.J. and RR. Christian. 2020. Water Quality Sampling - integrated measurements for the Virginia Coast, 1992-2019. Virginia Coast Reserve Long-Term Ecological Research Project Data Publication knb-lter-vcr.247.14

wqdrivers_raw<-read.csv('wqdrivers.csv')
```

#Part 1: Statistical Water Quality Model
``` {r outlierassess}
#Plot to search for outliers from Sentinel-2 (S2)
ggplot(data=data[which (data$type=="S2"),], aes(x=sat, y=insitu))+
  geom_point()+
  geom_text(aes(label=sat),hjust=0, vjust=0)+
  theme_classic()
#Plot to search for outliers from Landsat-8 (L8)
ggplot(data=data[which (data$type=="L8"),], aes(x=sat, y=insitu))+
  geom_point()+
  geom_text(aes(label=sat),hjust=0, vjust=0)+
  theme_classic()

data<-data[-73,] #Remove outliers, row 73, where insitu=0.36 m and L8=3.7m
dataoutlier<-read.csv("matchup.csv") #data with outlier
lmodel_outlier<-lm(insitu~sat+type+sat:type,dataoutlier) #model with outlier

model2<-lm(insitu~sat,data[data$type=="L8",]) #defining model, just using Landsat-8 data. no outlier
point_1 = c(3.742281, 0.36) #outlier data
data1 = rbind(data[data$type=="L8",], point_1) #bind data with outlier
model_1 = lm(insitu ~ sat, data = data1) #define model with outlier

#must run lines all together:
#plotting regression line with outlier, and regression line without outlier in order to see how much it changes the model
#the following code to plot model with and without outlier is modified from: https://github.com/daviddalpiaz/appliedstats/blob/master/diagnostics.Rmd

pdf(file="outlier.pdf",width=7,height=5)
plot(insitu ~ sat, data = data1, cex = 2, pch = 20, col = "grey", ylim = c(0,2),
     main = "",xlab="Satellite-derived Secchi depth (m)",
ylab=expression(paste(italic("In situ"), " Secchi depth (m)")))
points(x = point_1[1], y = point_1[2], pch = 1, cex = 4, col = "black", lwd = 2)
abline(model2, col = "black", lwd = 2)
abline(model_1, lty = 2, col = "red2", lwd = 2)
legend("topleft", c("No Outlier", "With Outlier"),
       lty = c(1, 2), col = c("black", "red2"))
```
```{r region}
#create new variable "region", assign NAs to all rows
data$region<-NA
#assign each site to "Ocean Inlet (OC)," "Lagoon (L)," or "Mainland Creek (MC)"
data<-data%>%
mutate(region=ifelse(site==5 | site==6 | site==12 | site==17, "OI", ifelse(site==16, "L", ifelse(site==2 | site==13, "MC", NA))))
#factor site and region
data$site<-factor(data$site)
data$region<-factor(data$region)
```

```{r modelmatchup, echo=FALSE}
#Basic statistics, subsetting data to find mean and standard deviation (sd) of just landsat-8 or sentinel-2
mean(data[which (data$type=="L8"),]$sat)
sd(data[which (data$type=="L8"),]$sat)
mean(data[which (data$type=="S2"),]$sat)
sd(data[which (data$type=="S2"),]$sat)
mean(data$insitu)
sd(data$insitu)

#Pearson product moment correlations of satellite and in situ, complete.obs removes NAs
cor.test(data$sat, data$insitu, method = "pearson", use = "complete.obs")
#Landsat-8 only
cor.test(data[which (data$type=="L8"),]$sat, data[which (data$type=="L8"),]$insitu, method = "pearson", use = "complete.obs")
#Sentinel-2 only
cor.test(data[which (data$type=="S2"),]$sat, data[which (data$type=="S2"),]$insitu, method = "pearson", use = "complete.obs")

#Factor source, which can be landsat, sentinel, or in situ
histdat$source<-factor(histdat$source)
#Create three different histograms of Secchi depths, one for each "source"
ggplot(histdat, aes(x=source, y=secchi, fill=source))+ #use fill to separate boxes for each "source"
  geom_boxplot(show.legend=FALSE)+ #hide the legend
  theme_classic()+ #figure with no grid lines and white background
  ylab("Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=30),axis.text.y = element_text(size=30))+ #adjust size of y axis title
  xlab("")+ #leave x-axis label blank
  theme(axis.text.x = element_text(size=30)) #adjust size ofx-axis labels

#Plot all matchups with 1:1 line
ggplot(data=data, aes(x=sat, y=insitu))+
  geom_point(aes(color=type),size=3)+ #color observations by satellite type
  theme_classic()+ 
  theme(aspect.ratio = 1)+ #square plot
  geom_abline()+ #1:1 line
  xlab("Satellite Secchi Depth (m)")+
  ylab("In Situ Secchi Depth (m)")
```

```{r modelbuild, echo=FALSE}
#Backwards model selection. beginning with interaction effects, removed non-significant variables one by one
data$type<-factor(data$type)
#Took site out - not testing site, creating a general model.
#linear regression
lmodel1<-lm(insitu~sat+type+days+sat:type+sat:days+type:days,data)
car::Anova(lmodel1,type="III") #use Type III sum of squares
lmodel2<-lm(insitu~sat+type+days+sat:type+type:days,data)
car::Anova(lmodel2,type="III")
lmodel3<-lm(insitu~sat+type+days+sat:type,data) 
car::Anova(lmodel3,type="III")
lmodel4<-lm(insitu~sat+type+sat:type,data)
car::Anova(lmodel4,type="III")
lmodel5<-lm(insitu~sat+type,data)
car::Anova(lmodel5,type="III")
lmodel6<-lm(insitu~sat,data)
car::Anova(lmodel6,type="III")

#best model using the Akaike information criterion
AIC(lmodel1,lmodel2,lmodel3,lmodel4,lmodel5,lmodel6)

#Defining the best model. We went with model 4, Interaction effect between satellite Zsd and satellite type had P=0.095. We also showed that Sentinel-2 predicts higher Secchi depths than Landsat-8. Lastly, Sentinel-2 predictions are more accurate than Landsat-8 predictions (see below)
model<-lmodel4
summary(model)

#Separate-satellite models to compare accuracy between L8 vs. S2 in predictions 
l8model<-lm(insitu~sat,data[data$type=="L8",]) #simple regression using satellite zsd to predict in situ zsd
summary(l8model)
plot(data[data$type=="L8",]$insitu,data[data$type=="L8",]$sat) #scatterplot satellite vs. in situ zsd
s2model<-lm(insitu~sat,data[data$type=="S2",])
summary(s2model)
plot(data[data$type=="S2",]$insitu,data[data$type=="S2",]$sat)
```



##Checking model assumptions
```{r modelassumptions}
#standardize model residuals
Emodel<-rstandard(model) 
#histogram of standardized residuals
hist(Emodel,xlab="Residuals", main="Histogram of Residuals")
#qqline to test for normality of residuals
qqnorm(Emodel)
qqline(Emodel)

#plot model residuals by fitted model values to test for homogeneity of variance
plot(x=fitted(model),y=resid(model,type="pearson"))
abline(a=0, b=0, lty=3)
#boxplot to view mean and distribution by site
boxplot(data$insitu~data$site, xlab="Site", ylab="In Situ Secchi Depth (m)")

#Autocorrelation by site
#split data by site
split.site<-split(data,data$site)
#set margin sizes for autocorrelation function (ACF) graphs
par(mar=c(1,1,1,1))
#S3 class of indexed totally ordered observations of irregular time series. Done by site
ts2<-zoo(split.site$'2'$insitu,split.site$'2'$date)
#autocorrelation function (ACF) graph
acf(ts2, na.action=na.omit, main="Auto-correlation plot for residuals, Site 2")
ts5<-zoo(split.site$'5'$insitu,split.site$'5'$date)
acf(ts5, na.action=na.pass, main="Auto-correlation plot for residuals, Site 5")
#had to remove duplice in situ values because zoo orders by in situ Secchi depth and cannot handle values that are not unique
ts6<-zoo(split.site$'6'[split.site$'6'$insitu!=1.05,]$insitu,split.site$'6'[split.site$'6'$insitu!=1.05,]$date)
acf(ts6, na.action=na.pass, main="Auto-correlation plot for residuals, Site 6")
ts12<-zoo(split.site$'12'$insitu,split.site$'12'$date)
acf(ts12, na.action=na.pass, main="Auto-correlation plot for residuals, Site 12")
ts13<-zoo(split.site$'13'$insitu,split.site$'13'$date)
acf(ts13, na.action=na.pass, main="Auto-correlation plot for residuals, Site 13")
ts16<-zoo(split.site$'16'$insitu,split.site$'16'$date)
acf(ts16, na.action=na.pass, main="Auto-correlation plot for residuals, Site 16")
ts17<-zoo(split.site$'17'$insitu,split.site$'17'$date)
acf(ts17, na.action=na.pass, main="Auto-correlation plot for residuals, Site 17")
```

```{r modelstats}
#Model stats
summary(model) #model summary
car::Anova(model,type="III") #type three sum of squares
#generate regression and ANOVA tables in APA format
apa.reg.table(model, filename = "RegTable_APA.doc", table.number = 2)
apa.aov.table(model, filename = "AOVTable_APA.doc", table.number = 4)

#Predictions from model 

#create new data frame for predictions
preds <- expand.grid(insitu = NA,
                     sat = seq(from = min(data$sat), to = max(data$sat), by = (max(data$sat) - min(data$sat)) / 100),
                     site = unique(data$site),
                     type=unique(data$type))
#predict secchi depth values (in situ values, y) from model (with satellite secchi depths as predictor variable, x). generate confidence and prediction intervals
insitupreds <- data.frame(predict(model, newdata = preds, interval='confidence'), preds$sat,preds$type)
insitupreds2 <- data.frame(predict(model , newdata = preds, interval='prediction'), preds$sat,preds$type)
#generate fit for graphing model
insitupreds$preds.insitu<-insitupreds$fit #confidence intervals
insitupreds2$preds.insitu<-insitupreds2$fit #prediction intervals

#same procedure as above, just for separate satellie models.
#create new data frame for predictions
l8preds <- expand.grid(insitu = NA,
                     sat = seq(from = min(data$sat), to = max(data$sat), by = (max(data$sat) - min(data$sat)) / 100),
                     site = unique(data$site))
s2preds <- expand.grid(insitu = NA,
                     sat = seq(from = min(data$sat), to = max(data$sat), by = (max(data$sat) - min(data$sat)) / 100),
                     site = unique(data$site))
insitupredsl8 <- data.frame(predict(l8model, newdata = l8preds, interval='confidence'), l8preds$sat)
insitupredss2 <- data.frame(predict(s2model , newdata = s2preds, interval='confidence'), s2preds$sat)
#generate fit for graphing model
insitupredsl8$preds.insitu<-insitupredsl8$fit #confidence intervals
insitupredss2$preds.insitu<-insitupredss2$fit #prediction intervals

#include predictions into main dataframe
data$preds <- NA
data$preds<-predict(model)

#plotting residuals
data$resid<-NA
data$resid<-data$preds-data$insitu
ggplot(aes(x=sat,y=resid),data=data)+
  geom_point()+
  ylab("Residuals (Model Zsd - In situ Zsd)")+
  xlab("Satellite Zsd (m)")+theme_classic()
```


```{r modelevaluation}
#Root mean square error calculations, by site and region
rmse(data$insitu,data$preds) #overall
rmse(data$insitu,data$sat) #unadjusted satellite algorithm models
rmse(data[data$site=="2",]$insitu,data[data$site=="2",]$preds)
rmse(data[data$site=="5",]$insitu,data[data$site=="5",]$preds)
rmse(data[data$site=="6",]$insitu,data[data$site=="6",]$preds)
rmse(data[data$site=="12",]$insitu,data[data$site=="12",]$preds)
rmse(data[data$site=="13",]$insitu,data[data$site=="13",]$preds)
rmse(data[data$site=="16",]$insitu,data[data$site=="16",]$preds)
rmse(data[data$site=="17",]$insitu,data[data$site=="17",]$preds)
rmse(data[data$region=="OI",]$insitu,data[data$region=="OI",]$preds)
rmse(data[data$region=="L",]$insitu,data[data$region=="L",]$preds)
rmse(data[data$region=="MC",]$insitu,data[data$region=="MC",]$preds)

# Mean absolute percent error (difference) calculations
mape(data$insitu,data$preds) #model, overall
mape(data$insitu,data$sat) #unadjusted satellite algorithm models
mape(data[data$site=="2",]$insitu,data[data$site=="2",]$preds)
mape(data[data$site=="5",]$insitu,data[data$site=="5",]$preds)
mape(data[data$site=="6",]$insitu,data[data$site=="6",]$preds)
mape(data[data$site=="12",]$insitu,data[data$site=="12",]$preds)
mape(data[data$site=="13",]$insitu,data[data$site=="13",]$preds)
mape(data[data$site=="16",]$insitu,data[data$site=="16",]$preds)
mape(data[data$site=="17",]$insitu,data[data$site=="17",]$preds)
mape(data[data$region=="OI",]$insitu,data[data$region=="OI",]$preds)
mape(data[data$region=="L",]$insitu,data[data$region=="L",]$preds)
mape(data[data$region=="MC",]$insitu,data[data$region=="MC",]$preds)

#Plot predictions vs. observations
r<-data.frame(r="r = 0.57")
satlabels<- c(L8 = "Landsat-8", S2 = "Sentinel-2")
ggplot(data=data,aes(x=insitu,y=preds))+
  geom_point(aes(color=type))+
    scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  geom_abline()+
  theme_classic()+
  guides(color=guide_legend(title="Satellite"))+
    theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+
    xlab("Model predictions of Secchi depth (m)")+
  labs(y=expression(paste(italic("In situ"), " Secchi depth (m)")))+ #use "expression" with "paste" to italicize in situ
geom_text(data=r, mapping=aes(x=0.4, y=1.5, label=r), size=6, hjust   = 0, vjust   = 0)+
  theme(aspect.ratio = 1)+
  ylim(0.4,1.6)+
  xlim(0.4,1.6)
ggsave(file="Modelpreds.pdf",width=5,height=5)

#correlation coefficient
cor.test(data$insitu,data$preds)
#reliability index, https://www.rdocumentation.org/packages/qualV/versions/0.3-3/topics/GRI
library(qualV)
GRI(data$insitu,data$preds)
#modeling efficiency, http://www.imsbio.co.jp/RGM/R_rdfile?f=hydroGOF/man/hydroGOF-package.Rd&d=R_CC, https://www.rdocumentation.org/packages/hydroGOF/versions/0.4-0/topics/NSE
library(hydroGOF)
#idk if the code matches though
NSE(data$preds,data$insitu)
mNSE(data$preds,data$insitu)
```

```{r modelplots1}
#dataframe of text to put on graph with ggplot
mainlabels<-data.frame(rmse="RMSE = 0.21 m",mapd="MAPD = 25%",nl="N (L8) = 85",ns="N (S2) = 38", dash="--- 1:1 line")

satlabels<- c(L8 = "Landsat-8", S2 = "Sentinel-2")
ggplot(data=data, aes(x=sat,y=insitu)) + 
  #color by type, put in aes command so ggplot considers this information as part of the data. this means that there will be a legend displaying the information
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=14),legend.text=element_text(size=14),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=16), axis.text.x=element_text(size=16))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  ylim(0,1.7)+
  theme(axis.title.y = element_text(size=16),axis.text.y=element_text(size=16))+ #defining attributes for y axis label
  #change data to insitupreds2 if you want to plot prediction intervals instead of confidence intervals
  geom_ribbon(data=insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2.9,], aes(x=preds.sat, y=preds.insitu, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) + #graph confidence intervals, data frame with predicted values and confidence intervals. alpha specifies how light/dark the color of the ribbon is
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2.9,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_ribbon(data=insitupreds[insitupreds$preds.type=="S2",], aes(x=preds.sat, y=preds.insitu, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) + #graph confidence intervals
  geom_line(data = insitupreds[insitupreds$preds.type=="S2",], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_abline(linetype="dashed", size=1)+ #1:1 line
  geom_point(aes(x=3.742281, y=0.36), colour="forestgreen",shape=8,size=5)+ #plotting the outlier with an asterick (shape=8)
  labs(subtitle = expression(paste(R[adj]^2 == "31%")))+ #use expression command to plot "adj" as subscript and 2 as superscript
  theme(plot.subtitle=element_text(size=18, hjust=0.05, vjust=-12))+ #plot and adjust position of R2
  #plotting text- define position of each string
  geom_text(data=mainlabels, mapping=aes(x=0.1, y=1.39+0.04, label=mapd), size=6, hjust   = 0, vjust   = 0)+
  geom_text(data=mainlabels, mapping=aes(x=0.1, y=1.26+0.04, label=rmse), size=6, hjust   = 0, vjust   = 0)+
  geom_text(data=mainlabels, mapping=aes(x=0.1, y=1.13+0.04, label=nl), size=6, hjust   = 0, vjust   = 0)+
  geom_text(data=mainlabels, mapping=aes(x=0.1, y=1.0+0.04, label=ns), size=6, hjust   = 0, vjust   = 0)+
  geom_text(data=mainlabels, mapping=aes(x=0.1, y=0.85+0.04, label=dash), size=6, hjust   = 0, vjust   = 0)+
  theme(aspect.ratio = 0.45)

#Plot of in situ Secchi depth vs Satellite Secchi depth 
l8<-ggplot(data=data[data$type=="L8",], aes(x=sat,y=insitu)) + 
  #color by type, put in aes command so ggplot considers this information as part of the data. this means that there will be a legend displaying the information
  geom_point(color="forestgreen", size=2)+
  theme_classic()+ #white, no gridlines
  xlab("Landsat-8 Secchi depth (m)")+
  theme(axis.title.x = element_text(size=16), axis.text.x=element_text(size=16))+ #defining attributes for x axis label
       labs(y=expression(paste(italic("In situ"), " Secchi depth (m)")))+
          ylim(0,1.7)+
  theme(axis.title.y = element_text(size=16),axis.text.y=element_text(size=16))+ #defining attributes for y axis label
          #layer to graph confidence intervals, alpha specifies how light/dark the color of the ribbon is:
  geom_ribbon(data=insitupredsl8, aes(x=l8preds.sat, y=fit, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) +
    #geom_ribbon(data=insitupreds[insitupreds$preds.type=="L8",], aes(x=preds.sat, y=preds.insitu, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) + #graph confidence intervals
          #prediction line:
         # geom_line(data = insitupreds[insitupreds$preds.type=="L8",], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen")
  geom_line(data = insitupredsl8, aes(x = l8preds.sat, y =fit), size = 1,color="forestgreen") + #prediction line, from landsat-8 specific predictions
          geom_abline(linetype="dashed", size=1)+ #1:1 line+
          geom_point(aes(x=3.742281, y=0.36), colour="forestgreen",shape=8,size=5)+ #plotting the outlier with an asterick (shape=8)
          theme(aspect.ratio = 1) 
        
se2<-ggplot(data=data[data$type=="S2",], aes(x=sat,y=insitu)) + 
          geom_point(color="darkorange2", size=2)+
          theme_classic()+ #white, no gridlines
          xlab("Sentinel-2 Secchi depth (m)")+
          theme(axis.title.x = element_text(size=16),axis.text.x=element_text(size=16))+ 
                labs(y=expression(paste(italic("In situ"), " Secchi depth (m)")))+
                  ylim(0,1.7)+
          xlim(0,3.5)+
                  theme(axis.title.y = element_text(size=16),axis.text.y=element_text(size=16))+ #defining attributes for y axis label
                  #geom_ribbon(data=insitupreds[insitupreds$preds.type=="S2",], aes(x=preds.sat, y=preds.insitu, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) + #graph confidence intervals
  geom_ribbon(data=insitupredss2, aes(x=s2preds.sat, y=fit, ymin=lwr, ymax=upr), fill="grey", alpha=0.4) + #graph confidence intervals
   geom_line(data = insitupredss2, aes(x = s2preds.sat, y =fit), size = 1,color="darkorange2") +
                 # geom_line(data = insitupreds[insitupreds$preds.type=="S2",], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
                  geom_abline(linetype="dashed", size=1)+
                  theme(aspect.ratio = 1) 

l8+se2 #patchwork: https://patchwork.data-imaginist.com/


```

``` {r siteplots}
#Plot by site
#data frame to label graphs, and position text on graphs
sitelabels<-data.frame(site=c("2","5","6","12","13","16","17"), sitelabs=c("2 (Mainland Creek)", "5 (Ocean Inlet)", "6 (Ocean Inlet)","12 (Ocean Inlet)","13 (Mainland Creek)", "16 (Lagoon)", "17 (Ocean Inlet)"),rmsesite=c("RMSE = 0.24 m","RMSE = 0.20 m","RMSE = 0.23 m","RMSE = 0.18 m","RMSE = 0.18 m","RMSE = 0.20 m","RMSE = 0.21 m"), nsite=c("N = 13","N = 20","N = 22","N = 18","N = 12","N = 19","N = 19"), mapdsite=c("MAPD = 55%", "MAPD = 20%", "MAPD = 20%", "MAPD = 20%", "MAPD = 29%", "MAPD = 21%", "MAPD = 21%"))

#same code as main graph, but subsetted site.
#copy code for every graph. take away prediction line of S2 for site 2 and site 13, which only have 1 S2 observation
#add outlier to graph of site 6
s2<-ggplot(data=data[data$site=="2",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen")+#line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="2",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+#graph values from data frame of labels, just labels associated with site 2
  geom_text(data=sitelabels[sitelabels$site=="2",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="2",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="2",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
   xlim(0,3)+
  ylim(0,1.6)+
   theme(aspect.ratio = 1)

s5<-ggplot(data=data[data$site=="5",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2.4,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2",], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="5",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="5",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="5",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="5",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  theme(aspect.ratio = 1)

s6<-ggplot(data=data[data$site=="6",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8",], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2"&insitupreds$preds.sat<2.6,], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_point(aes(x=3.742281, y=0.36), colour="forestgreen",shape=8,size=5)+ 
  geom_text(data=sitelabels[sitelabels$site=="6",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="6",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="6",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="6",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  theme(aspect.ratio = 1)

s12<-ggplot(data=data[data$site=="12",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+ 
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<3,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2"&insitupreds$preds.sat<2.8,], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="12",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="12",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="12",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="12",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  theme(aspect.ratio = 1)

s13<-ggplot(data=data[data$site=="13",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+ 
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="13",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="13",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="13",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="13",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
 xlim(0,3)+
  theme(aspect.ratio = 1)

s16<-ggplot(data=data[data$site=="16",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2.6,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2"&insitupreds$preds.sat<2.5,], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="16",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="16",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="16",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="16",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  xlim(0,3)+
  theme(aspect.ratio = 1)

s17<-ggplot(data=data[data$site=="17",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8",], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2",], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_text(data=sitelabels[sitelabels$site=="17",], mapping=aes(x=0.1, y=1.55, label=sitelabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="17",], mapping=aes(x=0.1, y=1.37, label=mapdsite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="17",], mapping=aes(x=0.1, y=1.25, label=rmsesite), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=sitelabels[sitelabels$site=="17",], mapping=aes(x=0.1, y=1.13, label=nsite), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  theme(aspect.ratio = 1)

#patchwork for more info see: https://patchwork.data-imaginist.com/articles/guides/assembly.html
wrap_plots(s2, s5, s6, s12,s13,s16,s17,plot_spacer())+guide_area()+plot_layout(guides='collect')+plot_annotation(tag_levels='A')+plot_layout(ncol = 4)
```

```{r regionplot}
#Plot by water type
#data frame with figure labels, and text to be plotted on graphs
regionlabels<-data.frame(region=c("L","MC","OI"), regionlabs=c("Lagoon", "Mainland Creek", "Ocean Inlet"),rmseregions=c("RMSE = 0.20 m","RMSE = 0.21 m","RMSE = 0.20 m"), nregions=c("N = 19","N = 25", "N = 79"), mapdregions=c("MAPD = 21%","MAPD = 43%","MAPD = 20%"))

#same as above, subsetted by "region"
#lagoon sites
lagoon<-ggplot(data=data[data$region=="L",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
geom_abline(linetype="dashed", size=1)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+ 
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2.6,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2"&insitupreds$preds.sat<2.6,], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  geom_text(data=regionlabels[regionlabels$region=="L",], mapping=aes(x=0.1, y=1.53, label=regionlabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="L",], mapping=aes(x=0.1, y=1.38, label=mapdregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="L",], mapping=aes(x=0.1, y=1.27, label=rmseregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="L",], mapping=aes(x=0.1, y=1.16, label=nregions), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  xlim(0,3)+
  theme(aspect.ratio = 1)

#take out S2 prediction line, only two MC observations
mainlandcreek<-ggplot(data=data[data$region=="MC",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  geom_abline(linetype="dashed", size=1)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+
  geom_line(data = insitupreds[insitupreds$preds.type=="L8"&insitupreds$preds.sat<2,], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_text(data=regionlabels[regionlabels$region=="MC",], mapping=aes(x=0.1, y=1.53, label=regionlabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="MC",], mapping=aes(x=0.1, y=1.38, label=mapdregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="MC",], mapping=aes(x=0.1, y=1.27, label=rmseregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="MC",], mapping=aes(x=0.1, y=1.16, label=nregions), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  xlim(0,3)+
  theme(aspect.ratio = 1)

oceaninlet<-ggplot(data=data[data$region=="OI",], aes(x=sat,y=insitu)) + 
  geom_point(aes(color = type), size=2)+
  geom_abline(linetype="dashed", size=1)+
  scale_colour_manual(breaks = c("L8", "S2"),
                      values = c("forestgreen", "darkorange2"),
                      name="",
                      labels=satlabels) +
  guides(color=guide_legend(title="Satellite"))+ #adding legend title
  theme_classic()+ #white, no gridlines
  theme(legend.title=element_text(size=12),legend.text=element_text(size=12),legend.position="bottom")+ #legend attributes
  xlab("Satellite Secchi Depth (m)")+
  theme(axis.title.x = element_text(size=12), axis.text.x=element_text(size=12))+ #defining attributes for x axis label
  ylab("In Situ Secchi Depth (m)")+
  theme(axis.title.y = element_text(size=12),axis.text.y=element_text(size=12))+ 
  geom_line(data = insitupreds[insitupreds$preds.type=="L8",], aes(x = preds.sat, y =preds.insitu), size = 1,color="forestgreen") + #line of predicted values
  geom_line(data = insitupreds[insitupreds$preds.type=="S2",], aes(x = preds.sat, y =preds.insitu), size = 1,color="darkorange2") + #line of predicted values
  labs(title="C")+
  geom_text(data=regionlabels[regionlabels$region=="OI",], mapping=aes(x=0.1, y=1.53, label=regionlabs), size=5, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="OI",], mapping=aes(x=0.1, y=1.38, label=mapdregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="OI",], mapping=aes(x=0.1, y=1.27, label=rmseregions), size=4, hjust   = 0, vjust   = 0)+
  geom_text(data=regionlabels[regionlabels$region=="OI",], mapping=aes(x=0.1, y=1.16, label=nregions), size=4, hjust   = 0, vjust   = 0)+
  ylim(0,1.6)+
  theme(aspect.ratio = 1)

#patchwork for more info see: https://patchwork.data-imaginist.com/articles/guides/assembly.html
regions<-wrap_plots(lagoon,mainlandcreek,oceaninlet)+guide_area()+plot_layout(guides='collect')+plot_annotation(tag_levels='A')+plot_layout(ncol = 3) #ncol assigns number of columns to arrange plots in, plot_annotation assigns subplots labels A-D
ggsave(filename="region.pdf",regions,width=14,height=10)

```
#Part 2: Out of sample validation with time series modeling
```{r gams}

#use dplyr to filter out all observations used to build model
sat_timedata2<-sat_timedata%>%
  dplyr::filter(date!="4/7/13") %>%
  dplyr::filter(date!="4/1/14") %>%
  dplyr::filter(date!="12/13/14") %>%
  dplyr::filter(date!="6/23/15") %>%
  dplyr::filter(date!="2/18/16") %>%
  dplyr::filter(date!="12/18/16") %>%
  dplyr::filter(date!="8/15/17") %>%
  dplyr::filter(date!="4/28/18") %>%
  dplyr::filter(date!="9/3/18") %>%
  dplyr::filter(date!="5/1/19") %>%
 dplyr::filter(date!="8/12/16") %>%
  dplyr::filter(date!="10/15/16") %>%
  dplyr::filter(date!="5/3/20") %>%
  dplyr::filter(date!="7/20/19") %>%
  dplyr::filter(date!="7/22/20")

#calculate model predictions, or adjusted secchi depths called 'modelsecchi'
sat_timedata2$sat<-NA
sat_timedata2$sat<-sat_timedata2$satsecchi
sat_timedata2$type<-NA
sat_timedata2$type<-'L8'
sat_timedata2$modelsecchi<-NA
sat_timedata2$modelsecchi<-predict(model,sat_timedata2)
preds<-data.frame(predict(model,sat_timedata2,interval="prediction"))

#read in situ data
insitu_timedata_all<-read.csv('wqdrivers.csv')

#select in situ data only from 2013-present, same time period as satellite data
insitu_timedata<-insitu_timedata_all[insitu_timedata_all$decimaldate>2013,]

#Satellite GAM (General Additive Models)
#for more information, see https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/
knots <- list(yearday= c(0.5, 366.5)) #to specifiy interval to assign knots over
satgam<-gam(modelsecchi~s(yearday,bs="cc",k=10)+s(decimaldate,bs="tp",k=10)+ti(yearday,decimaldate,bs=c('cc','tp'),k=c(15,15)),data=sat_timedata2,method = 'REML', knots = knots) #model equation: s= smoothing factors for decimal date (interannual variability) and yearday (seasonal trends). Tensor product (ti) to account for interaction between the two
set.seed(1) #gam.check will produce different results because checking with randomized values, so use set.seed to keep constant 
gam.check(satgam) #if k-index is much lower than one, less of a chance that the model is accurate. want higer p-value
summary(satgam) 
plot(satgam, scheme=1)

#gam with only sites with satellite data
insitu_timedata2<-insitu_timedata%>%
  dplyr::filter(station!="CM") %>%
  dplyr::filter(station!="CSH") %>%
  dplyr::filter(station!="CSM") %>%
  dplyr::filter(station!="GC") %>%
  dplyr::filter(station!="NC") %>%
  dplyr::filter(station!="NM") %>%
  dplyr::filter(station!="OH") %>%
  dplyr::filter(station!="PCB") %>%
  dplyr::filter(station!="PCH") %>%
  dplyr::filter(station!="PCM") %>%
  dplyr::filter(station!="PCT") %>%
  dplyr::filter(station!="RCC") %>%
  dplyr::filter(station!="SH")
write.csv(insitu_timedata2,file="i.csv")

#see above, same procedure as satellite gam
knots2 <- list(yearday= c(0.5, 366.5))
insitugam<-bam(secchi~s(yearday,bs="cc",k=10)+s(decimaldate,bs="tp",k=10)+ti(yearday,decimaldate,bs=c('cc','tp'),k=c(10,10)),data=insitu_timedata2,method = 'REML', knots = knots2)
set.seed(1)
gam.check(insitugam)
summary(insitugam)
plot(insitugam, scheme=1)

#get model predictions
modelpsat_dd<-get_gam_predictions(satgam,decimaldate,series_length = 300) #model predictions by decimal date
modelpsat_yd<-get_gam_predictions(satgam,yearday,series_length = 365) #model predictions by yearday
modelpinsitu_dd<-get_gam_predictions(insitugam2,decimaldate,series_length = 300)
modelpinsitu_yd<-get_gam_predictions(insitugam2,yearday,series_length = 365) 

sd(modelpsat_yd$modelsecchi) #standard deviation of gam predictions
sd(modelpinsitu_yd$secchi)

#graphing in situ Zsd by decimal date
x1<-ggplot()+
  xlab("Time")+
  ylab("In Situ Secchi Depth (m)")+
  geom_point(data=insitu_timedata2,aes(x=decimaldate,y=secchi),color='blue')+ #raw data, in sample
  geom_ribbon(data=modelpinsitu_dd,aes(x=decimaldate,ymin=CI_lower,ymax=CI_upper),fill='gray',alpha=0.6)+ #plot confidence intervals, alpha sets transparency
  geom_line(data=modelpinsitu_dd,aes(x=decimaldate,y=secchi),color='black',size=1)+ #line created from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +#assigning number of labeled tick marks on x axis
  theme_classic()+
   labs(title = "B")+
  theme(plot.title = element_text(size=18))+
   labs(title = "Interannual Variability\n\nA")+
 theme(aspect.ratio = 0.7)
  
#graphing
preds$decimaldate<-NA
preds$decimaldate<-sat_timedata2$decimaldate
preds$yearday<-NA
preds$yearday<-sat_timedata2$yearday

#graphing satellite (model-adjusted) Zsd by decimal date
x2<-ggplot()+
  xlab("Time")+
  ylab("Model-derived Secchi Depth (m)")+
  geom_point(data=sat_timedata2,aes(x=decimaldate,y=modelsecchi),color='red')+ #plotting raw data in red
   geom_ribbon(data=modelpsat_dd,aes(x=decimaldate,ymin=CI_lower,ymax=CI_upper),fill='gray',alpha=0.6)+ #plot error band, alpha sets transparency
  geom_line(data=modelpsat_dd,aes(x=decimaldate,y=modelsecchi),color='black',size=1)+ #line created from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +#assigning number of labeled tick marks on x axis
  theme_classic()+
  theme(aspect.ratio = 0.7)+
  labs(title="B")+
   theme(plot.title = element_text(size=18))

#plotting satellite (model-adjusted) Zsd by decimal date with error bars on each point
x2error<-ggplot()+
      geom_linerange(data=preds,aes(x=decimaldate,ymin=lwr, ymax=upr), color="darkgray", position=position_dodge(.9)) +
  #plot error bars on each point
  xlab("Time")+
  ylab("Model-derived Secchi Depth (m)")+
  geom_point(data=sat_timedata2,aes(x=decimaldate,y=modelsecchi),color='red')+ #plotting raw data in red
  geom_line(data=modelpsat_dd,aes(x=decimaldate,y=modelsecchi),color='black',size=1)+ #line created from model predictions
 scale_x_continuous(limits=c(2013,2020.6),breaks = scales::pretty_breaks(n = 10)) +#assigning number of labeled tick marks on x axis
    ylim(0.1,1.7)+
  theme_classic()+
  theme(aspect.ratio = 0.7)+
    labs(title="C")+
   theme(plot.title = element_text(size=18))

# plotting in situ Zsd by year day
x3<-ggplot()+
  xlab("Year Day")+
  ylab("In Situ Secchi Depth (m)")+
  geom_point(data=insitu_timedata2,aes(x=yearday,y=secchi),color='blue')+
  geom_ribbon(data=modelpinsitu_yd,aes(x=yearday,ymin=CI_lower,ymax=CI_upper),fill='gray',alpha=0.6)+#plot confidence intervals, alpha sets transparency
  geom_line(data=modelpinsitu_yd,aes(x=yearday,y=secchi),color='black',size=1)+#line created from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_classic()+
    labs(title = "    Seasonal Trends\n\nD")+
    theme(plot.title = element_text(size=18))+
 theme(aspect.ratio = 0.7)

#plotting satellite (model-adjusted) Zsd by year day
x4<-ggplot()+
  xlab("Year Day")+
  ylab("Model-derived Secchi Depth (m)")+
 geom_point(data=sat_timedata2,aes(x=yearday,y=modelsecchi),color='red')+ #raw data
     geom_ribbon(data=modelpsat_yd,aes(x=yearday,ymin=CI_lower,ymax=CI_upper),fill='gray',alpha=0.6)+
  geom_line(data=modelpsat_yd,aes(x=yearday,y=modelsecchi),color='black',size=1)+#line created from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +#assigning number of labeled tick marks on x axis
  theme_classic()+
  theme(aspect.ratio = 0.7)+
  labs(title="E")+
   theme(plot.title = element_text(size=18)) #assigning size of title
  
#plotting satellite (model-adjusted) Zsd by year day with error bars on each point
x4error<-ggplot()+
      geom_linerange(data=preds,aes(x=yearday,ymin=lwr, ymax=upr), color="darkgray",width=.2, position=position_dodge(.9)) +
  xlab("Year Day")+
  ylab("Model-derived Secchi Depth (m)")+
 geom_point(data=sat_timedata2,aes(x=yearday,y=modelsecchi),color='red')+ #raw data
  geom_line(data=modelpsat_yd,aes(x=yearday,y=modelsecchi),color='black',size=1)+#line created from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +#assigning number of labeled tick marks on x axis
  theme_classic()+
  ylim(0.1,1.7)+
  theme(aspect.ratio = 0.7)+
  labs(title="F")+
   theme(plot.title = element_text(size=18)) #assigning size of title

#patchwork
wrap_plots(x1,x3,x2,x4,x2error,x4error)+plot_layout(ncol=2)
#plot_annotation assigns subplots labels A-D
wrap_plots(x1,x3,x2,x4)+plot_layout(ncol=2) #same but without panels with error bars
```

Modeling all in situ data, 1992-2020
```{r insitugam}
insitugam_all<-bam(secchi~s(yearday,bs="cc",k=25)+s(decimaldate,bs="tp",k=25)+ti(yearday,decimaldate,bs=c('cc','tp'),k=c(25,25)),data=insitu_timedata_all,method = 'REML', knots = knots2)
set.seed(1)
gam.check(insitugam_all)
summary(insitugam_all)
modelpinsitu_dd_all<-get_gam_predictions(insitugam_all,decimaldate,series_length = 300) #predict secchi depths for decimal dates
modelpinsitu_yd_all<-get_gam_predictions(insitugam_all,yearday,series_length = 365) #predict secchi depths for yeardays

ggplot()+
  xlab("Year Day")+
  ylab("Secchi Depth (m)")+
  geom_point(data=insitu_timedata_all,aes(x=yearday,y=secchi),color='gray')+
  geom_ribbon(aes(x=yearday,ymin=secchi-0.1,ymax=secchi+0.1),data=modelpinsitu_yd_all, fill = "blue",alpha=0.25)+ #error bars associated with 0.1m error on in situ Secchi depth measurements
  geom_line(data=modelpinsitu_yd_all,aes(x=yearday,y=secchi),color='blue',size=1)+ #line from model predictions
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  theme_classic()+
  theme(aspect.ratio = 1.5)

ggplot()+
  xlab("Decimal Date")+
  ylab("Secchi Depth (m)")+
geom_point(data=insitu_timedata_all,aes(x=decimaldate,y=secchi),color='gray')+
    geom_ribbon(aes(x=decimaldate,ymin=secchi-0.1,ymax=secchi+0.1),data=modelpinsitu_dd_all, fill = "blue",alpha=0.25)+
  geom_line(data=modelpinsitu_dd_all,aes(x=decimaldate,y=secchi),color='blue',size=1)+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 20)) +
  theme_classic()+
  theme(aspect.ratio = 1.5)
```

#Part 3: Satellite Comparison
```{r satsecchi}
#remove NaNs with dplyr
secchidata <- comparedata %>%
  dplyr::filter(!is.na(Sentinel)) %>%
  dplyr::filter(!is.na(Landsat))
#ggplot
big<-ggplot(data=secchidata, aes(x=Landsat,y=Sentinel))+
  geom_point()+
  theme_classic()+
  xlim(0,4)+
  ylim(0,4)+
  geom_abline(lty=2)+
  geom_smooth(method='lm', formula= y~poly(x,2),color="red")+
  xlab("Landsat-8 Secchi depth (m)")+
  ylab("Sentinel-2 Secchi depth (m)")+
  theme(axis.title.x = element_text(size=16),axis.title.y = element_text(size=16))+
  labs(title="Satellite-derived Secchi depths", subtitle = expression(paste(R[adj]^2 == "90%")), caption=expression(paste("y = ","-1.0x"^"2"," + 13.5x"," + 2.2")))+
 theme(plot.title=element_text(size=18,hjust=0.04,vjust=-9),plot.subtitle=element_text(size=18, hjust = 0.04, vjust=-15), plot.caption=element_text(size=18, hjust = 0.04, vjust=118, color="black"))+
  theme(aspect.ratio = 1)
```

``` {r satbands}
#remove NaNs with filter in dplyr
band1data <- comparedata %>%
  dplyr::filter(!is.na(l443)) %>%
  dplyr::filter(!is.na(s443))
#pearsons correlation
cor.test(band1data$l443, band1data$s443, method = "pearson", use = "complete.obs")
#ggplot for Band 1
band1graph<-ggplot(data=band1data, aes(x=l443,y=s443))+
  geom_point()+
  theme_classic()+
  geom_abline(lty=2)+ #lty=2 makes it a dashed line
  xlab(expression(paste("Landsat-8 Rrs", " (","sr"^"-1",")")))+
  ylab(expression(paste("Sentinel-2 Rrs", " (","sr"^"-1",")")))+
  labs(title="Band 1", subtitle="r=0.67")
band1graph

#Band 2
#remove NaNs
band2data <- comparedata %>%
  dplyr::filter(!is.na(l482)) %>%
  dplyr::filter(!is.na(s482))
#pearsons correlation
cor.test(band2data$l482, band2data$s482, method = "pearson", use = "complete.obs")
#ggplot
band2graph<-ggplot(data=band2data, aes(x=l482,y=s482))+
  geom_point()+
  theme_classic()+
  geom_abline(lty=2)+
  xlab(expression(paste("Landsat-8 Rrs", " (","sr"^"-1",")")))+
  ylab(expression(paste("Sentinel-2 Rrs", " (","sr"^"-1",")")))+
  theme(aspect.ratio = 1)+
  labs(title="Band 2", subtitle="r=0.74")
band2graph

#Band 3
#remove NaNs
band3data <- comparedata %>%
  dplyr::filter(!is.na(l561)) %>%
  dplyr::filter(!is.na(s561))
#pearsons correlation
cor.test(band3data$l561, band3data$s561, method = "pearson", use = "complete.obs")
#graph
band3graph<-ggplot(data=band3data, aes(x=l561,y=s561))+
  geom_point()+
  theme_classic()+
  xlim(0,0.02)+
  ylim(0,0.02)+
  geom_abline(lty=2)+
  xlab(expression(paste("Landsat-8 Rrs", " (","sr"^"-1",")")))+
  ylab(expression(paste("Sentinel-2 Rrs", " (","sr"^"-1",")")))+
  theme(aspect.ratio = 1)+
  labs(title="Band 3", subtitle="r=0.72")

#Band 4
band4data <- comparedata %>%
  dplyr::filter(!is.na(l665)) %>%
  dplyr::filter(!is.na(s665))
#pearsons correlation
cor.test(band4data$l665, band4data$s665, method = "pearson", use = "complete.obs")
#graph
band4graph<-ggplot(data=band4data, aes(x=l665,y=s665))+
  geom_point()+
  theme_classic()+
 xlim(0,0.015)+
 ylim(0,0.015)+
  geom_abline(lty=2)+
  xlab(expression(paste("Landsat-8 Rrs", " (","sr"^"-1",")")))+
  ylab(expression(paste("Sentinel-2 Rrs", " (","sr"^"-1",")")))+
  theme(aspect.ratio = 1)+
  labs(title="Band 4", subtitle="r=0.84")

#patchwork to organize graphs nicely 
#im with the band
wrap_plots(band1graph,band2graph,band3graph,band4graph)+plot_layout(ncol=4)+plot_annotation(tag_levels = "A")
```

#Part 4: Atmospheric Correction Assessment 
```{r atmocorrection}
#Comparing Secchi depths
plot(atmocorrect$insitu,atmocorrect$acolite)
atmocorrect_no_outlier<-atmocorrect[-40,] #row 40 corresponds to outlier in this dataset
cor.test(atmocorrect_no_outlier$insitu,atmocorrect_no_outlier$acolite) #pearsons product moment correlation for acolite-derived Secchi depths
atmocorrect_no_outlier$site<-factor(atmocorrect_no_outlier$site)
cor.test(atmocorrect_no_outlier$insitu,atmocorrect_no_outlier$acolite)
cor.test(atmocorrect_no_outlier$insitu,atmocorrect_no_outlier$seadas)#pearsons product moment correlation for seadas-derived Secchi depths

atmositeonly<-atmocorrect_no_outlier %>%
  dplyr::filter(site!="3")%>%
  dplyr::filter(site!="4")%>%
dplyr::filter(site!="7")%>%
  dplyr::filter(site!="8")%>%
  dplyr::filter(site!="11")%>%
  dplyr::filter(site!="14")%>%
  dplyr::filter(site!="15")

cor.test(atmositeonly$insitu,atmositeonly$acolite)
  
mean(atmocorrect_no_outlier$acolite,na.rm=TRUE)
sd(atmocorrect_no_outlier$acolite,na.rm=TRUE) #standard deviation
mean(atmocorrect_no_outlier$seadas,na.rm=TRUE)
sd(atmocorrect_no_outlier$seadas,na.rm=TRUE)
mean(atmocorrect_no_outlier$insitu,na.rm=TRUE)
sd(atmocorrect_no_outlier$insitu,na.rm=TRUE)

ac<-lm(insitu~acolite,data=atmocorrect_no_outlier) #single atmo correction model, using satellite zsd from ACOLITE to predict in situ zsd from all sites
summary(ac)
ac2<-lm(insitu~acolite,data=atmositeonly)#single atmo correction model, using satellite zsd from ACOLITE to predict in situ zsd, from sites with only seadas values too
summary(ac2)
sdas<-lm(insitu~seadas,data=atmocorrect_no_outlier) #single atmo correction model, using satellite zsd from SeaDAS to predict in situ zsd
summary(sdas)

#rmse and mapd- rather than using "rmse" and "mape", explicitly writing out formula in order to use na.rm (remove NA's)
sqrt(sum((atmocorrect_no_outlier$acolite - atmocorrect_no_outlier$insitu)^2 , na.rm = TRUE ) / nrow(atmocorrect_no_outlier)) 
mean((abs(atmocorrect_no_outlier$insitu-atmocorrect_no_outlier$acolite)/atmocorrect_no_outlier$insitu),na.rm=TRUE)
mean((abs(atmocorrect_no_outlier$insitu-atmocorrect_no_outlier$seadas)/atmocorrect_no_outlier$insitu),na.rm=TRUE)

labels <- c(seadas = "SeaDAS", acolite = "ACOLITE",dash="1:1 Line")
text<-data.frame(seadas="SeaDAS: r = 0.49, p = 0.017",acolite='ACOLITE: r = 0.39, p = 0.021') #dataframe to plot text elements on ggplot
ggplot(data=atmocorrect_no_outlier,aes(y=insitu))+
 geom_point(aes(x=seadas),color="green4")+ #green points from seadas
 geom_point(aes(x=acolite),color="plum3")+ #purple points from acolite
 geom_smooth(aes(x=seadas,color='seadas'),method='lm',se=F)+ #plotting regression line, assigning color to 'seadas' to be assigned below in scale_colour_manual
  geom_smooth(aes(x=acolite,color='acolite'),method='lm',se=F)+ #plotting regression line, assigning color to 'acolite' to be assigned below in scale_colour_manual
  geom_abline(aes(slope=1,intercept=0,color='dash'),linetype="dashed",size=1,show.legend = FALSE)+#1:1 line
  #assigning colors to geom_smooths
  scale_colour_manual(breaks = c("seadas", "acolite","dash"), 
                      values = c("darkgreen", "darkorchid4","black"),
                      name="",
                      labels=labels)+
  #plotting text
  geom_text(data=text, mapping=aes(x=2, y=1.1, label=seadas), size=4.5, hjust   = 0, vjust   = 0)+
  geom_text(data=text, mapping=aes(x=2, y=1.2, label=acolite), size=4.5, hjust   = 0, vjust   = 0)+
  xlab("Satellite Secchi depth (m)")+
  labs(y=expression(paste(italic("In situ"), " Secchi depth (m)")))+
  theme(axis.title.x = element_text(size=20),axis.title.y = element_text(size=20))+
   geom_point(aes(x=3.74228092,y=0.36),shape=4,color="green4",size=4)+ #plotting outlier from seadas
  geom_point(aes(x=1.7740263,y=0.36),shape=4,color="darkorchid4",size=4)+ #plotting outlier from acolite
 #theme(aspect.ratio = 1)+
  theme_classic()+
  theme(legend.position="bottom",legend.text=element_text(size=12))
ggsave("SeaDASvsAcolite.pdf",width=5,height=4) #save pdf

#Comparing bands
labels2<-c(r443 = "Rrs(443)", r482 = "Rrs(482)",r561="Rrs(561)",r665="Rrs(655)")
text2<-data.frame(line="1:1 Line")
ggplot()+
  geom_abline(linetype="dashed")+
  geom_point(data=atmocorrect_no_outlier,aes(x=srrs443,y=arrs443,color="r443"))+ #plot rrs443, assign label 'r443' in order to assign color in scale_colour_manual
  geom_point(data=atmocorrect_no_outlier,aes(x=srrs482,y=arrs482,color='r482'))+
  geom_point(data=atmocorrect_no_outlier,aes(x=srrs561,y=arrs561,color='r561'))+
  geom_point(data=atmocorrect_no_outlier,aes(x=srrs655,y=arrs655,color='r665'))+
 geom_point(aes(x=0.008422001,y=0.015502657),shape=4,color="dodgerblue",size=4)+ #rrs's associated with outliers
  geom_point(aes(x=0.011251556,y=0.017705237),shape=4,color="dodgerblue4",size=4)+
  geom_point(aes(x=0.013641334,y=0.018730832),shape=4,color="forestgreen",size=4)+
  geom_point(aes(x=0.00416089,y=0.009018892),shape=4,color="red",size=4)+
  scale_colour_manual(breaks = c("r443", "r482","r561","r665"),
                      values = c("dodgerblue", "dodgerblue4","forestgreen","red"),
                      name="",
                      labels=labels2)+
  xlab(expression(paste("SeaDAS Rrs", " (","sr"^"-1",")")))+ #using 'expression' in order to format exponents
  ylab(expression(paste("ACOLITE Rrs", " (","sr"^"-1",")")))+
  theme(axis.title.x = element_text(size=18),axis.ticks.x=element_text(size=16))+ #adjusting size of axis titles and tick mark labels
  theme(axis.title.y = element_text(size=18),axis.ticks.y=element_text(size=16))+
  geom_text(data=text2,mapping=aes(x=0.016, y=0.014, label=line),size=4)+
  theme(aspect.ratio = 1)+
  theme_classic()+
  theme(legend.position="bottom",legend.text=element_text(size=12))
ggsave("atmocorrectbands.pdf",width=5,height=5)
```

#Part 5: Water Quality Assessment
```{r wqgraphs}
#remove nh4 and po4 measurements that fall outside the detection limit
wqdrivers<-wqdrivers_raw %>%
  mutate(pom = replace(pom, pom<0, NA))%>%
  mutate(pim = replace(pim, pim<0, NA))%>%
    mutate(tss = replace(tss, tss<0, NA))%>%
  mutate(tss = replace(tss, pom<0, NA))%>%
  mutate(tss = replace(tss, pim<0, NA))%>%
  mutate(nh4 = replace(nh4, nh4<0.36, NA))%>%
  mutate(nh4 = replace(nh4, nh4>45, NA))%>%
  mutate(po4 = replace(po4, po4<0.16, NA))%>%
  mutate(po4 = replace(po4, po4>20, NA))
#calculate total suspended solids sites with satellite retrievals vs. without
wqdrivers$satret<-NA
#grouping sites into two groups: those with satellite data (seadas) and those without. called satret= S (sat data) or NS (no sat data)
wqdrivers<-wqdrivers%>%
mutate(satret=ifelse(station=="CRM" | station=="LC" | station=="MI" | station=="QI"| station=="RB"| station=="SS"| station=="SSI", "S", ifelse(station=="CM"| station=="CSM"| station=="GC"| station=="NC"| station=="NM"| station=="OH"| station=="PCB"| station=="PCM"| station=="RCC"| station=="SH", "NS", NA)))
ag1<-aggregate(tss ~ satret, wqdrivers, mean) #tss mean for sites with sat data and without
write.csv(ag1,"tssmean.csv",row.names=F)
ag2<-aggregate(tss ~ satret, wqdrivers, sd) 
write.csv(ag2,"tsssd.csv",row.names=F)
#calculating average total suspended solids for each station
ag1<-aggregate(tss ~ station, wqdrivers, mean)
write.csv(ag1,"tssmean.csv",row.names=F)
ag2<-aggregate(tss ~ station, wqdrivers, sd) 
write.csv(ag2,"tsssd.csv",row.names=F)

boxlabels<-data.frame(region=c("CM","CRM","CSM","GC","LC","MI","NC","NM","OH","PCB","PCM","QI","RB","RCC","SH","SS","SSI"), boxlabs=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17")) #using site numbers instead of station codes as labels on graph
legend<-c("No Satellite Data Available","Satellite Data Available")
ggplot(data=wqdrivers[wqdrivers$satret!="N",],aes(x=station,y=log(tss)))+
  geom_boxplot(aes(fill=satret))+
  xlab("Site")+
  ylab("Total Suspended Solids (mg/L, log scale)")+
  scale_x_discrete(labels=boxlabels$boxlabs)+
  theme_classic()+
  theme(legend.position="bottom")+
  guides(fill=guide_legend(title="Site Type"))
ggsave(filename="tss.pdf",width=5,height=4)
  
#calculate average depth for each station
#be wary, diff #, tides, possibly units of measure- use median instead
aggregate(depth ~ station, wqdrivers, summary)
boxplot(depth~station,wqdrivers)
aggregate(secchi ~ station, wqdrivers, summary)
boxplot(secchi~station,wqdrivers)
#remove negative tss,pom, and pim values

#oxygen calculations from rMR package
wqdrivers$percentsat <- DO.saturation(DO.mgl = wqdrivers$do,
                         temp.C = wqdrivers$dotemp, salinity=wqdrivers$sctsal, salinity.units="pp.thou",elevation.m = 0) #percent oxygen saturation- not used in apparent oxygen utilization measurement, but could be useful anyway
wqdrivers$oxy_equil<-Eq.Ox.conc(temp.C=wqdrivers$dotemp, elevation.m = 0, out.DO.meas = "mg/L", salinity = wqdrivers$sctsal, salinity.units = "pp.thou") #calculate oxygen equilibrium saturation concentration at given water temperature and salinity
wqdrivers$aou<-wqdrivers$oxy_equil-wqdrivers$do #difference between oxygen equilibrium sat concentration and dissolved oxygen
wqdrivers$aou <- replace(wqdrivers$aou,wqdrivers$aou < -50, NA) #remove outlier

#standardizing the data
standardData<-wqdrivers[,c("measureDate","yearday","secchi","chlor_a", "tss", "aou","scttemp","sctsal","sctcond","pom","pim","phaeopigments_a","TDN","nh4","po4")] #subset data to be standardized
standardData[,c("secchi","chlor_a", "tss", "aou","scttemp","sctsal","sctcond","pom","pim","phaeopigments_a","TDN","nh4","po4")] <- lapply(standardData[,c("secchi","chlor_a","tss", "aou","scttemp","sctsal","sctcond","pom","pim","phaeopigments_a","TDN","nh4","po4")], function(x) c(scale(x))) #standardize data

#Plotting individual graphs, grouping parameters
# In order to plot two y axises in R, you must transform the second axis by some multiple of the first, and shift the parameters you are plotting as well. Transforming an axis with negative values is really tricky... I had to use some creative transformations for x2, x3, and x4. x1 was more simple, just simply multiplying the first axis by 2.5/30 and dividing the parameter on the secondary axis (Secchi depth) by that number. For the others, transformations were more complicated! some hand written calculations, some trial by error!
labels1<-c("Temperature","Secchi depth")
#used to transform the left axis #s to the right axis
coeff<-2.5/30
x1<-
  ggplot(data=wqdrivers, aes(x=yearday))+
  geom_point(aes(y=secchi/coeff),color="gray")+ #divide by coefficient
  geom_smooth(aes(y=secchi/coeff,color="secchi"),method='loess',se=F)+
  geom_point(aes(y=scttemp),color="lightsteelblue1")+
  geom_smooth(aes(y=scttemp,color="scttemp"),se=F)+
  scale_colour_manual(breaks = c("scttemp", "secchi"),
                      values = c("blue", "black"),
                      name="",
                      labels=labels1) +
  scale_y_continuous(name="Temperature C\u00b0",breaks = scales::pretty_breaks(n = 5),sec.axis = sec_axis(~.*coeff,name="Secchi depth, m",breaks = scales::pretty_breaks(n = 5)))+ #multiply secondary axis by coefficient
   theme_classic()+
  theme(legend.position="top")+ #move legend to top
  theme(aspect.ratio = 1)+ #square graph
   scale_x_continuous(breaks = scales::pretty_breaks(n = 6))+ #amount of tick marks on x axis
  xlab("Year day")+
  labs(title="A) Temperature")

#equations in y and trans: https://stackoverflow.com/questions/54612136/how-to-scale-a-secondary-axis-with-ggplot2-second-axis-has-negative-values
#had to play around with different transformations, weird because tough to translate neg axis to pos one...
#secondary axis has to be translated by using the first axis,.. only one to one transformations allowed!!

labels <- c(sctsal = "Salinity", sctcond = "Conductivity", aou = "Apparent oxygen\nutilization",secchi="Secchi\ndepth")
coeff4<-1.5
x2<-ggplot()+
geom_point(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff4)),color="gray")+ #plot secchi depths with transformation, opposite formula to axis transformation, secchi is on secondary axis
  geom_smooth(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff4),color="secchi"),method='loess',se=F)+ #loess smooth, secondary axis
 geom_smooth(data=standardData,aes(x=yearday,y=sctsal,color="sctsal"),method='loess',se=F)+ #primary axis, no transformation necessary
 geom_smooth(data=standardData,aes(x=yearday,y=sctcond,color="sctcond"),method='loess',se=F)+#primary axis, no transformation
geom_smooth(data=standardData,aes(x=yearday,y=aou,color="aou"),method='loess',se=F)+#primary axis, no transformation
  #assign colors to each smooth:
  scale_colour_manual(breaks = c("sctsal", "sctcond", "aou","secchi"),
                      values = c("palegreen", "seagreen4", "royalblue","black"),
                      name="",
                      labels=labels) +
  theme_classic()+
  theme(legend.position="top")+
  theme(aspect.ratio = 1)+
 scale_y_continuous(name="Z-Score",breaks = scales::pretty_breaks(n = 10),sec.axis = sec_axis(trans = ~.*coeff4+2,name="Secchi depth, m",breaks = scales::pretty_breaks(n = 5)))+ #assign transformation to secondary axis and # of tick mark labels on y-axis
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6))+
  xlab("Year day")+
  labs(title="B) Salinity, conductivity, and oxygen utilization")+
  theme(plot.title = element_text(hjust = 0.5))

#same code for x3 and x4 as x2
coeff6<-2
labels2<-c("POM","PIM","TSS","Secchi\ndepth")
x3<-
  ggplot()+
  geom_point(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff6)),color="gray")+
  geom_smooth(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff6),color="secchi"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=pom,color="pom"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=pim,color="pim"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=tss,color="tss"),method='loess',se=F)+
  scale_colour_manual(breaks = c("pom", "pim", "tss","secchi"),
                      values = c("royalblue", "tomato", "purple4","black"),
                      name="",
                      labels=labels2) +
  theme_classic()+
  theme(legend.position="top")+ 
  theme(aspect.ratio = 1)+
  scale_y_continuous(name="Z-Score",breaks = scales::pretty_breaks(n = 10),sec.axis = sec_axis(trans = ~.*coeff6+2,name="Secchi depth, m",breaks = scales::pretty_breaks(n = 5)))+
  xlab("Year Day")+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6))+
  labs(title="C) Suspended particulates")
  
coeff5<-1.1
labels3<-c("TDN","PO4","NH4","Phaeopigments","Chlorophyll-a","Secchi depth")
x4<-
  ggplot()+
  geom_point(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff5)),color="gray")+
  geom_smooth(data=wqdrivers,aes(x=yearday,y=((secchi-2)/coeff5),color="secchi"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=TDN,color="TDN"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=po4,color="po4"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=nh4,color="nh4"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=phaeopigments_a,color="phaeopigments_a"),method='loess',se=F)+
  geom_smooth(data=standardData,aes(x=yearday,y=chlor_a,color="chlor_a"),method='loess',se=F)+
  scale_colour_manual(breaks = c("TDN", "po4", "nh4","phaeopigments_a","chlor_a","secchi"),
                      values = c("royalblue", "tomato", "purple4","palegreen","seagreen4","black"),
                      name="",
                      labels=labels3) +
  theme_classic()+
  theme(legend.position="top")+ 
  theme(aspect.ratio = 1)+
  scale_y_continuous(name="Z-Score",breaks = scales::pretty_breaks(n = 10),sec.axis = sec_axis(trans = ~.*coeff5+2,name="Secchi depth, m",breaks = scales::pretty_breaks(n = 5)))+
  xlab("Year day")+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6))+
  labs(title="D) Nutrients and pigments")

#patchwork
(x1+x2)/(x3+x4)
x1+x3+x2+x4+plot_layout(ncol=2) #assign plots in two columns
#wrap_plots(x1,x3,x2,x1)+guide_area()+plot_layout(guides='collect')+plot_annotation(tag_levels='A')+plot_layout(ncol = 2)
```

